- hosts: 
  - workstations
  - computenodes
  become: yes
  tasks:
   - name: pkcon-refresh
     shell: "pkcon -p -y refresh force"
     register: pkcon_refresh
     failed_when: pkcon_refresh.rc != 0 and pkcon_refresh.rc != 5
   - name: pkcon-update
     shell: "pkcon -p -y update"
     register: pkcon_update
     failed_when: pkcon_update.rc != 0 and pkcon_update.rc != 5
   - name: Remove dependencies that are no longer required
     apt:
      autoremove: yes
      autoclean: yes
   - name: update drivedb
     command: wget https://www.smartmontools.org/export/5028/branches/RELEASE_6_5_DRIVEDB/smartmontools/drivedb.h -O /var/lib/smartmontools/drivedb/drivedb.h
   - name: update-pciids
     command: update-pciids
   - name: update-usbids
     command: update-usbids
   - name: update-initram-fs
     command: update-initramfs -k all -c
   - name: update-grub
     command: update-grub
   - name: purge configs
     shell: "dpkg -l | grep '^rc' | awk '{print $2}' | xargs dpkg --purge"
     ignore_errors: yes
