- name: Install HWE
  shell: apt-get install --install-recommends linux-generic-hwe-18.04 xserver-xorg-hwe-18.04

- name: Install workstation apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
  vars:
    packages:
      - gle-graphics
      - texlive-full
      - x2goserver
      - x2goserver-xsession
      - imagej
      - partitionmanager
      - language-pack-en
      - language-pack-fr
      - language-pack-de
      - feh
      - xfig
      - meshlab
      - lxde-core
      - google-chrome-stable
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-med
      - hunspell-fr
      - libreoffice
      - libreoffice-style-breeze
      - inkscape
      - gimp
      - vlc
