- name: nfs-common installed
  apt:  pkg=nfs-common state=latest

- name: autofs installed
  apt: pkg=autofs state=latest

- name: create place for homdirs
  file: path=/home/cic state=directory

- name : setup auto.master
  copy: src=files/auto.master dest=/etc/auto.master
  notify: restart autofs

- name: create /data
  file: path=/data state=directory

- name: autofs /data
  copy: src=files/auto.data dest=/etc/auto.data
  notify: restart autofs

- name: create /backup
  file: path=/backup state=directory

- name: autofs /backup
  copy: src=files/auto.backup dest=/etc/auto.backup
  notify: restart autofs

- name: autofs /home
  copy: src=files/auto.home dest=/etc/auto.home
  notify: restart autofs

- name: autofs direct maps
  copy: src=files/auto.direct  dest=/etc/auto.direct
  notify: restart autofs

- name: configure nfs-common
  copy: src=files/nfs-common dest=/etc/default/nfs-common
