- apt: upgrade=dist update_cache=yes cache_valid_time=3600

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: install common packages
  apt:  pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - python-pip
    - pv
    - openntpd
    - xauth
    - lm-sensors
    - thermald
    - tmux
    - screen
    - apcupsd
    - landscape-common
    - ssmtp
    - unattended-upgrades
    - lvm2
    - exfat-utils
    - imagemagick
    - irssi
    - openssh-server
    - ansible
    - environment-modules
    - quota
    - parallel
    - cvs
    - subversion
    - make
    - gcc
    - nodejs
    - build-essential
    - gfortran
    - git
    - aptitude
    - intel-microcode
    - libnss-myhostname
    - nmap
    - openjdk-7-jdk
    - lrzip
    - htop
    - iotop
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi-core
    - dkms
    - python-numpy
    - python-scipy
    - python-matplotlib
    - ipython
    - ipython-notebook
    - python-pandas
    - python-sympy
    - python-nose
    - python-scitools
    - vim
    - exuberant-ctags
    - vim-doc
    - vim-scripts
    - fonts-inconsolata
    - octave
    - pspp
    - emacs
    - git
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - ntfs-3g
    - dosfstools
    - dmraid
    - dmsetup
    - kpartx
    - freeipmi
    - ipmitool
    - automake
    - autoconf
    - libtool
    - debconf-utils
    - pam-kwallet
    - python-argcomplete
    - python-optcomplete
#libraries
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - cmake
    - cmake-curses-gui
    - protobuf-c-compiler
    - protobuf-compiler
    - python-protobuf
    - netcdf-bin
    - libnetcdf-dev
    - libnetcdfc7
    - libnetcdff5
    - libnetcdfc++4
    - libhdf4-0
    - libhdf4-dev
    - libhdf5-7
    - libhdf5-dev
    - lib32gcc1
    - libblas-dev
    - liblapack-dev
    - libnetpbm10-dev
    - libpcre++0
    - bison
    - flex
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
    - libsqlite3-dev
    - libjpeg62
    - liblcms1
    - libperl4-corelibs-perl
    - tcl8.4
    - tcl8.5
    - tk8.4
    - tk8.5
    - libgdchart-gd2-xpm
    - libgiftiio0
    - libnewmat10ldbl
    - libnifti2
    - libqt4-qt3support
    - libqwt5-qt4
    - libgetopt-tabular-perl
    - libroot-math-matrix-dev
    - libgetopt-argvfile-perl
#torch deps
    - build-essential
    - gcc
    - curl
    - libreadline-dev
    - git
    - libqt4-core
    - libjpeg-dev
    - libpng-dev
    - ncurses-dev
    - libzmq3-dev
    - gfortran
    - unzip
    - gnuplot-qt
    - libsdl2-dev
    - libgraphicsmagick1-dev
    - libfftw3-dev
    - g++
    - libqt4-gui
    - libqt4-dev
    - libsox-fmt-all
    - libopenblas-base
    - libopenblas-dev
    - unzip
    - libssl0.9.8
    - cpanminus
#soge deps
    - db5.1-util
    - libdb5.1
    - libjemalloc1
    - tcsh
    - python-nipy
    - python-dipy
    - ifenslave
    - zlib1g-dev
    - libosmesa6-dev
    - watchdog
    - smartmontools
    - source-highlight

- name: remove problematic software
  apt:  pkg={{ item }} state=absent update_cache=yes cache_valid_time=3600
  with_items:
    - apparmor
    - apparmor-profiles
    - snapd

- cpanm: name="Math::Matrix"
